# Generated by Django 2.0.4 on 2018-04-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('comp', models.CharField(default='Title', max_length=32)),
                ('low', models.IntegerField()),
                ('high', models.IntegerField()),
                ('pos', models.CharField(default='Title', max_length=32)),
                ('addr', models.CharField(default='Title', max_length=32)),
                ('site', models.CharField(default='Title', max_length=32)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
