# Generated by Django 2.0.4 on 2018-04-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('avg_low', models.IntegerField()),
                ('avg_high', models.IntegerField()),
                ('site', models.CharField(max_length=32)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
